projectName = "mobile-wholesale-backend"

[[services]]
name = "backend"
type = "web"
env = "node"
path = "backend"
build = "npm install"
start = "npm start"
port = 5000

[services.environment]
MONGODB_URI = ""
JWT_SECRET = ""
