services:
  - type: web_service
    name: mobile-wholesale
    env: node
    repo: https://github.com/Nafis5858/Mobile-Wholesale
    branch: main
    path: .
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
